Repository alibaba/sentinel-golang, pull requests merged in 2020-10, with the labels that each got.

#265 Use path/filepath pkg to do file path related operations
  core/config/config.go
  core/log/metric/writer.go
  logging/logging.go
  util/file.go
Labels: kind/enhancement, to-review

#263 Mod: acquire -> batch
  api/api.go
  api/api_test.go
  core/base/context.go
  core/base/slot_chain.go
  core/base/slot_chain_test.go
  core/flow/slot.go
  core/flow/slot_test.go
  core/flow/standalone_stat_slot.go
  core/flow/tc_default.go
  core/flow/tc_throttling.go
  core/flow/traffic_shaping.go
  core/hotspot/slot.go
  core/hotspot/slot_test.go
  core/hotspot/traffic_shaping.go
  core/isolation/slot.go
  core/stat/stat_slot.go
  example/isolation/concurrency_limitation_example.go
Labels: kind/enhancement

#270 Refine naming for ext/datasource module
  ext/datasource/consul/consul.go
  ext/datasource/consul/consul_example_test.go
  ext/datasource/etcdv3/etcdv3.go
  ext/datasource/etcdv3/etcdv3_example.go
  ext/datasource/helper.go
Labels: area/data-source, kind/enhancement

#269 enhance datasource ut
  ext/datasource/datasource.go
  ext/datasource/datasource_test.go
  ext/datasource/helper_test.go
Labels: area/test

#267 Optimize logging debug by level pre-check
  core/hotspot/concurrency_stat_slot.go
  core/hotspot/slot.go
  logging/logging.go
  logging/logging_test.go
Labels: area/logging, area/performance

#276 Imp: cb state
  core/circuitbreaker/circuit_breaker.go
  core/circuitbreaker/circuit_breaker_test.go
Labels: kind/enhancement

#277 Refine pooled EntryOptions management
  api/api.go
Labels: kind/enhancement

#286 Enhance float number comparison
  adapter/echo/middleware_test.go
  adapter/gin/middleware_test.go
  adapter/grpc/client_test.go
  adapter/grpc/server_test.go
  adapter/micro/client_test.go
  adapter/micro/server_test.go
  core/circuitbreaker/circuit_breaker_test.go
  core/circuitbreaker/rule_manager_test.go
  core/flow/rule.go
  core/flow/tc_throttling.go
  core/flow/tc_throttling_test.go
  core/flow/tc_warm_up.go
  core/hotspot/rule_manager_test.go
  core/hotspot/rule_test.go
  core/hotspot/slot_test.go
  core/hotspot/traffic_shaping_test.go
  core/stat/base/bucket_leap_array_test.go
  core/stat/base/sliding_window_metric_test.go
  core/stat/base_node.go
  core/system/slot.go
  core/system/slot_test.go
  core/system/sys_stat.go
  core/system/sys_stat_test.go
Labels: kind/enhancement

#264 Feature： new slot chain
  api/api.go
  api/api_test.go
  api/slot_chain.go
  core/base/slot_chain.go
  core/base/slot_chain_test.go
  core/circuitbreaker/rule_manager.go
  core/circuitbreaker/slot.go
  core/circuitbreaker/stat_slot.go
  core/flow/rule_manager.go
  core/flow/slot.go
  core/flow/standalone_stat_slot.go
  core/hotspot/concurrency_stat_slot.go
  core/hotspot/rule_manager.go
  core/hotspot/slot.go
  core/isolation/rule_manager.go
  core/isolation/slot.go
  core/log/slot.go
  core/misc/slot_chain.go
  core/stat/stat_prepare_slot.go
  core/stat/stat_slot.go
  core/system/rule_manager.go
  core/system/slot.go
Labels: area/performance, kind/enhancement, kind/refactor, to-review

#288 Refine string builder usage in logging pkg
  logging/logging.go
  logging/logging_test.go
Labels: area/logging

#283 Abstract concurrency-related operations as ConcurrencyStat interface and polish StatNode
  core/base/stat.go
  core/base/stat_test.go
  core/isolation/slot.go
  core/stat/base_node.go
  core/stat/stat_slot.go
  core/system/slot.go
  core/system/slot_test.go
  example/hotspot_param_flow/concurrency/hotspot_params_concurrency_example.go
Labels: kind/api-change, kind/enhancement, kind/refactor

#292 add dingding group qr code
  README.md
Labels: area/document

#290 Enhance config API, support initialization by config parser
  api/init.go
  core/config/config.go
  core/config/config_test.go
Labels: area/configuration, kind/api-change, kind/enhancement

#291 Refine APIs of per-resource slot chain and improve rule slot registering logic in rule managers
  api/api.go
  api/slot_chain.go
  core/base/slot_chain.go
  core/base/slot_chain_test.go
  core/circuitbreaker/rule_manager.go
  core/flow/rule_manager.go
  core/hotspot/rule_manager.go
  core/isolation/rule_manager.go
  core/misc/resource_slot_chain.go
  core/misc/resource_slot_chain_test.go
  core/system/rule_manager.go
Labels: kind/enhancement, to-review

#296 enhance logging api and refine comments
  core/circuitbreaker/rule_manager.go
  core/isolation/rule_manager_test.go
  example/isolation/concurrency_limitation_example.go
  logging/logging.go
  logging/logging_test.go
  tests/core/circuitbreaker/circuitbreaker_slot_integration_test.go
  tests/maxsize_rule_list_benchmark_test.go
Labels: area/logging, to-review

#284 purge existing panic operations
  core/stat/base/atomic_window_wrap_array_test.go
  core/stat/base/bucket_leap_array.go
  core/stat/base/leap_array.go
  core/stat/base/metric_bucket.go
Labels: kind/enhancement

#298 Fix bug that StatIntervalInMs do not take effect in throttling checker
  core/flow/rule_manager.go
  core/flow/rule_manager_test.go
  core/flow/tc_throttling.go
  core/flow/tc_throttling_test.go
Labels: kind/enhancement

#293 unify logging content style
  api/tracer.go
  core/base/entry.go
  core/base/slot_chain.go
  core/circuitbreaker/circuit_breaker.go
  core/circuitbreaker/rule_manager.go
  core/config/config.go
  core/flow/rule_manager.go
  core/flow/slot.go
  core/flow/standalone_stat_slot.go
  core/hotspot/cache/lru.go
  core/hotspot/concurrency_stat_slot.go
  core/hotspot/rule_manager.go
  core/hotspot/slot.go
  core/hotspot/traffic_shaping.go
  core/isolation/rule_manager.go
  core/isolation/slot.go
  core/log/metric/aggregator.go
  core/log/metric/reader.go
  core/log/metric/searcher.go
  core/log/metric/writer.go
  core/stat/base/bucket_leap_array.go
  core/stat/base/sliding_window_metric.go
  core/stat/node_storage.go
  core/system/rule_manager.go
  core/system/sys_stat.go
  example/circuitbreaker/error_count/circuit_breaker_error_count_example.go
  example/circuitbreaker/error_ratio/circuit_breaker_error_ratio_example.go
  example/circuitbreaker/slow_rt_ratio/circuit_breaker_slow_rt_ratio_example.go
  example/hotspot_param_flow/concurrency/hotspot_params_concurrency_example.go
  example/hotspot_param_flow/qps_reject/hotspot_params_qps_reject_example.go
  example/hotspot_param_flow/qps_throttling/hotspot_params_qps_throttling_example.go
  example/isolation/concurrency_limitation_example.go
  ext/datasource/consul/consul.go
  ext/datasource/etcdv3/etcdv3.go
  ext/datasource/file/refreshable_file.go
  ext/datasource/file/refreshable_file_test.go
  ext/datasource/nacos/nacos.go
  ext/datasource/property.go
  util/auto_recover.go
Labels: area/logging, kind/enhancement, to-review

#307 Use internal errors pkg to create global error var
  core/base/stat.go
Labels: kind/enhancement

#305 Allow flow rule MaxQueueingTimeMs to be 0
  core/flow/rule.go
  core/flow/rule_manager.go
  core/flow/rule_manager_test.go
Labels: kind/bug

#302 Fix no limit of batch count in flow throttling checker
  core/flow/tc_throttling.go
  core/flow/tc_throttling_test.go
Labels: kind/bug

#303 migrate adapter to independent repo
  adapter/echo/middleware.go
  adapter/echo/middleware_example_test.go
  adapter/echo/middleware_test.go
  adapter/echo/option.go
  adapter/gin/middleware.go
  adapter/gin/middleware_example_test.go
  adapter/gin/middleware_test.go
  adapter/gin/option.go
  adapter/grpc/client.go
  adapter/grpc/client_test.go
  adapter/grpc/options.go
  adapter/grpc/server.go
  adapter/grpc/server_test.go
  adapter/micro/client.go
  adapter/micro/client_test.go
  adapter/micro/doc.go
  adapter/micro/options.go
  adapter/micro/server.go
  adapter/micro/server_test.go
  go.mod
  go.sum
  tests/adapter/micro/proto/test.pb.go
  tests/adapter/micro/proto/test.pb.micro.go
  tests/adapter/micro/proto/test.proto
Labels: area/integrations

#304 Remove datasource and migrate it to sentinel-group
  example/datasource/consul/datasource_consul_example.go
  example/datasource/etcdv3/datasource_etcdv3_example.go
  example/datasource/nacos/datasource_nacos_example.go
  ext/datasource/consul/consul.go
  ext/datasource/consul/consul_example_test.go
  ext/datasource/consul/consul_test.go
  ext/datasource/consul/option.go
  ext/datasource/etcdv3/etcdv3.go
  ext/datasource/etcdv3/etcdv3_example.go
  ext/datasource/nacos/nacos.go
  ext/datasource/nacos/nacos_test.go
  go.mod
  go.sum
Labels: area/data-source, kind/refactor

#273 Make map&slice with init capacity to decrease grow cost
  api/api.go
  core/circuitbreaker/circuit_breaker.go
  core/circuitbreaker/rule_manager.go
  core/flow/rule_manager.go
  core/hotspot/cache/lru.go
  core/hotspot/rule_manager.go
  core/isolation/rule_manager.go
  core/log/metric/aggregator.go
  core/log/metric/common.go
  core/log/metric/reader.go
  core/stat/base/leap_array.go
  core/stat/base/sliding_window_metric.go
  core/system/rule_manager.go
  ext/datasource/helper.go
  ext/datasource/hotspot_rule_converter.go
Labels: area/performance

#312 not supported retrieve and update windows system stat
  api/init.go
  core/system/slot.go
  util/safe.go
Labels: kind/bug
