Repository alibaba/sentinel-golang, pull requests merged in 2020-03, with the labels that each got.

#80 Add atomic bool in util
  util/atomic.go
  util/atomic_test.go
Labels: kind/enhancement, to-review

#78 Change the implementation of LoadRules in flow rule manager.go
  core/flow/rule_manager.go
Labels: to-review

#73 Dynamic datasource framework init
  core/base/property.go
  ext/datasource/datasource.go
  ext/datasource/property.go
  ext/datasource/property_test.go
  go.mod
  go.sum
  tests/testdata/extension/SystemRule.json
  tests/testdata/extension/SystemRule2.json
  tests/testdata/extension/SystemRule3.json
Labels: area/data-source, kind/feature, to-review

#56 Unify configuration
  api/init.go
  core/base/constant.go
  core/config/configuration.go
  core/config/configuration_test.go
  core/config/constant.go
  core/config/entity.go
  core/config/local_storage.go
  core/log/metric/reader.go
  core/log/metric/searcher.go
  core/log/metric/writer.go
  core/stat/base/bucket_leap_array.go
  core/stat/base/leap_array.go
  core/system/rule_manager.go
  example/sentinel.yml
  logging/config.go
  logging/logging.go
  tests/testdata/config/sentinel.yml
  tests/testdata/config/sentinel.yml.2
  util/auto_recover.go
Labels: area/configuration, to-review

#87 Polish code and comment of config and init package
  api/init.go
  core/config/config.go
  core/config/config_test.go
  core/config/constant.go
  core/config/entity.go
  core/log/metric/aggregator.go
  core/log/metric/writer.go
  util/file.go
Labels: kind/enhancement, to-review

#89 Enhance datasource framework.
  ext/datasource/datasource.go
  ext/datasource/property.go
  ext/datasource/property_test.go
Labels: kind/enhancement, to-review

#90 Add helper for system.SystemRule and flow.FlowRule in datasource
  core/flow/rule_manager.go
  core/system/rule_manager.go
  ext/datasource/helper.go
  ext/datasource/helper_test.go
  tests/testdata/extension/plugin/FlowRule.json
  tests/testdata/extension/plugin/SystemRule.json
Labels: area/data-source, to-review

#82 fix #49; implement gin adapter
  adapter/gin/middleware.go
  adapter/gin/middleware_example_test.go
  adapter/gin/middleware_test.go
  adapter/gin/option.go
  go.mod
  go.sum
Labels: area/integrations, to-review

#92 Hotfix: Fix bug for SystemRulesUpdater and FlowRulesUpdater
  ext/datasource/helper.go
  ext/datasource/helper_test.go
Labels: kind/bug, to-review

#81 fix #52, implement grpc adapter
  .gitignore
  adapter/grpc/client.go
  adapter/grpc/client_test.go
  adapter/grpc/options.go
  adapter/grpc/server.go
  adapter/grpc/server_test.go
  api/api.go
  go.mod
  go.sum
Labels: area/integrations, to-review

#86 refreshable file data source
  ext/datasource/datasource.go
  ext/datasource/datasource_test.go
  ext/datasource/file/refreshable_file.go
  ext/datasource/file/refreshable_file_test.go
  ext/datasource/mock.go
  ext/datasource/property_test.go
  go.mod
  go.sum
Labels: area/data-source, to-review

#96 Polish error Tracer
  api/tracer.go
  api/tracer_test.go
Labels: kind/enhancement

#72 polish the method LoadRules() in system rule manager.go (#71)
  core/system/rule_manager.go
  core/system/rule_manager_test.go
Labels: kind/enhancement, to-review

#98 Fix bugs and polish code in dubbo-go adapter
  adapter/dubbo/consumer_filter.go
  adapter/dubbo/consumer_filter_test.go
  adapter/dubbo/fallback.go
  adapter/dubbo/provider_filter.go
  adapter/dubbo/provider_filter_test.go
  adapter/dubbo/util.go
  adapter/dubbo/util_test.go
Labels: area/integrations, kind/bug, kind/enhancement

#101 Refine file datasource code and add ut
  ext/datasource/file/refreshable_file.go
  ext/datasource/file/refreshable_file_test.go
  go.mod
Labels: area/data-source, kind/enhancement

#102 Polish gRPC-go adapter
  adapter/grpc/client.go
  adapter/grpc/client_test.go
  adapter/grpc/options.go
  adapter/grpc/server.go
  adapter/grpc/server_test.go
Labels: area/integrations, kind/enhancement

#106 Format codebase by 'gofmt' command and add CI inspection for it
  .travis.yml
  adapter/gin/middleware.go
  adapter/gin/middleware_example_test.go
  adapter/gin/middleware_test.go
  adapter/gin/option.go
  core/log/metric/aggregator_test.go
  core/log/metric/common_test.go
  core/stat/resource_node.go
  core/stat/resource_node_test.go
  ext/datasource/helper_test.go
  logging/logging.go
Labels: kind/enhancement

#109 Polish code in some details
  adapter/dubbo/consumer_filter_test.go
  adapter/dubbo/provider_filter_test.go
  adapter/dubbo/util_test.go
  core/flow/rule_manager.go
  core/log/metric/aggregator.go
  core/log/metric/aggregator_test.go
  core/log/metric/reader.go
  core/stat/node_storage.go
  core/system/rule_manager.go
  core/system/rule_manager_test.go
Labels: kind/enhancement, to-review
