Repository alibaba/sentinel-golang, pull requests merged in 2020-04, with the labels that each got.

#95 Add adapter for echo framework
  adapter/echo/middleware.go
  adapter/echo/middleware_example_test.go
  adapter/echo/middleware_test.go
  adapter/echo/option.go
  go.mod
  go.sum
Labels: area/integrations, kind/feature

#18 Issue13 circuit breaker implementation
  core/circuit_breaker/circuit_breaker.go
  core/circuit_breaker/circuit_breaker_test.go
  core/circuit_breaker/rule.go
  core/circuit_breaker/rule_manager.go
  core/circuit_breaker/rule_manager_test.go
  core/circuit_breaker/rule_test.go
  core/circuit_breaker/slot.go
  go.mod
  go.sum
  util/uuid.go
Labels: area/circuit-breaking, to-review

#115 Etcdv3 datasource
  ext/datasource/datasource.go
  ext/datasource/error.go
  ext/datasource/etcdv3/etcdv3.go
  ext/datasource/etcdv3/etcdv3_example.go
  ext/datasource/file/refreshable_file.go
  ext/datasource/helper.go
  go.mod
  go.sum
Labels: area/data-source

#124 make EntryOptions support storing custom data before Sentinel.Entry()
  api/api.go
  core/base/context.go
  core/base/slot_chain_test.go
Labels: kind/enhancement

#139 Organize imports in groups
  .travis.yml
  adapter/echo/middleware_test.go
  adapter/grpc/server_test.go
  api/api_test.go
  api/init.go
  core/base/context_test.go
  core/base/metric_item_test.go
  core/base/slot_chain.go
  core/base/slot_chain_test.go
  core/circuit_breaker/circuit_breaker.go
  core/circuit_breaker/rule.go
  core/circuit_breaker/rule_manager.go
  core/circuit_breaker/rule_manager_test.go
  core/circuit_breaker/slot.go
  core/config/config.go
  core/flow/rule_manager_test.go
  core/flow/slot.go
  core/flow/tc_throttling.go
  core/flow/tc_throttling_test.go
  core/log/metric/aggregator.go
  core/log/metric/aggregator_test.go
  core/log/metric/common.go
  core/log/metric/reader.go
  core/log/metric/searcher.go
  core/log/metric/writer.go
  core/stat/base/atomic_window_wrap_array_test.go
  core/stat/base/bucket_leap_array.go
  core/stat/base/leap_array.go
  core/stat/base/metric_bucket.go
  core/stat/base/metric_bucket_test.go
  core/stat/base/sliding_window_metric.go
  core/stat/base_node.go
  core/stat/node_storage.go
  core/stat/resource_node.go
  core/stat/resource_node_test.go
  core/system/rule_manager.go
  core/system/slot_test.go
  core/system/sys_stat.go
  example/qps_limit_example.go
  ext/datasource/datasource.go
  ext/datasource/datasource_test.go
  ext/datasource/etcdv3/etcdv3.go
  ext/datasource/etcdv3/etcdv3_example.go
  ext/datasource/file/refreshable_file.go
  ext/datasource/file/refreshable_file_test.go
  ext/datasource/helper.go
  ext/datasource/helper_test.go
  ext/datasource/property.go
  ext/datasource/property_test.go
  logging/logging_test.go
  util/atomic_test.go
  util/util_test.go
Labels: kind/enhancement, to-review

#142 Add result token pool (#137)
  api/api.go
  core/base/result.go
  core/base/result_test.go
  core/base/slot_chain.go
  core/circuit_breaker/slot.go
  core/flow/slot.go
  go.mod
  go.sum
Labels: kind/enhancement, to-review
