Repository alibaba/sentinel-golang, pull requests merged in 2020-02, with the labels that each got.

#29 Add basic flow control module
  core/flow/rule.go
  core/flow/rule_manager.go
  core/flow/slot.go
  core/flow/tc_default.go
  core/flow/tc_throttling.go
  core/flow/traffic_shaping.go
Labels: kind/feature

#31 auto recover routine to avoid sentinel interrupt main process.
  util/auto_recover.go
  util/util_test.go
Labels: to-review

#33 Add system adaptive rule implementation
  core/system/rule.go
  core/system/rule_manager.go
  core/system/slot.go
  core/system/sys_stat.go
  go.mod
  go.sum
Labels: kind/feature, to-review

#34 Add metric log implementation
  core/base/metric_item_test.go
  core/log/metric/aggregator.go
  core/log/metric/common.go
  core/log/metric/common_test.go
  core/log/metric/reader.go
  core/log/metric/searcher.go
  core/log/metric/writer.go
  core/log/slot.go
Labels: kind/feature, to-review

#30 Refactor stat node and polish stat pkg
  core/base/stat.go
  core/stat/base/atomic_window_wrap_array_test.go
  core/stat/base/bucket_leap_array.go
  core/stat/base/bucket_leap_array_test.go
  core/stat/base/leap_array.go
  core/stat/base/leap_array_test.go
  core/stat/base/sliding_window_metric.go
  core/stat/base/sliding_window_metric_test.go
  core/stat/base_node.go
  core/stat/resource_node.go
  core/stat/resource_node_test.go
Labels: to-review

#39 Add throttling traffic shaping implementation
  core/flow/rule_manager.go
  core/flow/tc_throttling.go
  core/flow/tc_throttling_test.go
  util/time.go
Labels: area/flow-control, to-review

#40 Add general configuration definition and initialization mechanism
  core/config/entity.go
  core/config/local_storage.go
  util/string.go
Labels: area/configuration, to-review

#54 Change module to alibaba/sentinel-golang
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  api/api.go
  api/api_test.go
  api/init.go
  api/option.go
  api/slot_chain.go
  core/base/metric_item.go
  core/base/slot_chain.go
  core/config/local_storage.go
  core/flow/rule_manager.go
  core/flow/slot.go
  core/flow/tc_default.go
  core/flow/tc_throttling.go
  core/flow/tc_throttling_test.go
  core/flow/traffic_shaping.go
  core/log/metric/aggregator.go
  core/log/metric/common.go
  core/log/metric/reader.go
  core/log/metric/searcher.go
  core/log/metric/writer.go
  core/log/slot.go
  core/stat/base/atomic_window_wrap_array_test.go
  core/stat/base/bucket_leap_array.go
  core/stat/base/bucket_leap_array_test.go
  core/stat/base/leap_array.go
  core/stat/base/leap_array_test.go
  core/stat/base/metric_bucket.go
  core/stat/base/metric_bucket_test.go
  core/stat/base/sliding_window_metric.go
  core/stat/base/sliding_window_metric_test.go
  core/stat/base_node.go
  core/stat/node_storage.go
  core/stat/resource_node.go
  core/stat/resource_node_test.go
  core/stat/stat_prepare_slot.go
  core/stat/stat_slot.go
  core/system/rule_manager.go
  core/system/slot.go
  core/system/sys_stat.go
  example/qps_limit_example.go
  go.mod
  util/auto_recover.go
  util/util_test.go
Labels: to-review

#57 Add support for collecting CPU usage for SystemRule
  api/init.go
  core/config/entity.go
  core/config/local_storage.go
  core/system/sys_stat.go
  core/system/sys_stat_test.go
Labels: kind/enhancement

#53 Add unit test for metric log
  .gitignore
  core/log/metric/aggregator.go
  core/log/metric/aggregator_test.go
  core/log/metric/common.go
  core/log/metric/common_test.go
  coverage.sh
  tests/testdata/metric/app1-metrics.log.2020-02-14
  tests/testdata/metric/app1-metrics.log.2020-02-14.12
  tests/testdata/metric/app1-metrics.log.2020-02-14.32
  tests/testdata/metric/app1-metrics.log.2020-02-14.idx
  tests/testdata/metric/app1-metrics.log.2020-02-15
  tests/testdata/metric/app1-metrics.log.2020-02-16
  tests/testdata/metric/app1-metrics.log.2020-02-16.100
Labels: area/test, to-review

#60 Add dubbogo adapter
  .travis.yml
  adapter/dubbo/consumer_filter.go
  adapter/dubbo/consumer_filter_test.go
  adapter/dubbo/fallback.go
  adapter/dubbo/filter.go
  adapter/dubbo/provider_filter.go
  adapter/dubbo/provider_filter_test.go
  adapter/dubbo/util.go
  adapter/dubbo/util_test.go
  go.mod
  go.sum
Labels: area/integrations, to-review

#65 Add tracer and polish related code
  api/api.go
  api/api_test.go
  api/option.go
  api/tracer.go
  api/tracer_test.go
Labels: to-review

#59 Add unit test for common util
  util/file_test.go
  util/string_test.go
  util/time.go
  util/time_test.go
Labels: area/test, to-review

#64 add unit test for core/system
  core/system/rule_manager.go
  core/system/rule_manager_test.go
  core/system/rule_test.go
  core/system/slot_test.go
  core/system/sys_stat.go
  core/system/sys_stat_test.go
Labels: area/test, to-review
