Repository alibaba/sentinel-golang, pull requests merged in 2020-09, with the labels that each got.

#218 fix bug: incorrectly defined storeToken using uint in warmup flow control
  core/flow/rule_manager.go
  core/flow/tc_warm_up.go
  example/warm_up/qps_warm_up_example.go
Labels: kind/bug, to-review

#214 feat(adater): Implement go-micro adapter
  adapter/go_micro/client.go
  adapter/go_micro/client_test.go
  adapter/go_micro/options.go
  adapter/go_micro/proto/test.pb.go
  adapter/go_micro/proto/test.pb.micro.go
  adapter/go_micro/proto/test.proto
  adapter/go_micro/server.go
  adapter/go_micro/server_test.go
  go.mod
  go.sum
Labels: area/integrations, to-review

#220 update nacos example
  example/datasource/nacos/nacos_example.go
  ext/datasource/nacos/nacos_example.go
  ext/datasource/nacos/nacos_test.go
  go.sum
Labels: area/data-source

#227 refactoring: Delete "SlotName" in 'core/system/slot.go'.
  core/system/slot.go
  core/system/slot_test.go
Labels: kind/enhancement

#229 Migratet adapter dubbo-go
  adapter/dubbo/consumer_filter.go
  adapter/dubbo/consumer_filter_test.go
  adapter/dubbo/fallback.go
  adapter/dubbo/filter.go
  adapter/dubbo/provider_filter.go
  adapter/dubbo/provider_filter_test.go
  adapter/dubbo/util.go
  adapter/dubbo/util_test.go
  go.mod
  go.sum
Labels: area/integrations

#230 Update README.md
  README.md
Labels: area/document

#233 Remove field LimitOrigin in flow.Rule
  core/flow/rule.go
  core/flow/rule_manager.go
  ext/datasource/helper_test.go
  tests/testdata/extension/helper/FlowRule.json
Labels: area/flow-control, kind/enhancement

#223 Break down flow.ControlBehavior to flow.TokenCalculateStrategy and flow.ControlBehavior
  adapter/echo/middleware_test.go
  adapter/gin/middleware_test.go
  adapter/grpc/client_test.go
  adapter/grpc/server_test.go
  adapter/micro/client_test.go
  adapter/micro/server_test.go
  core/flow/rule.go
  core/flow/rule_manager.go
  core/flow/rule_manager_test.go
  core/flow/tc_default.go
  example/qps/qps_limit_example.go
  example/qps/qps_limit_example_test.go
  example/warm_up/qps_warm_up_example.go
  example/warm_up/qps_warm_up_example_test.go
  ext/datasource/helper_test.go
  tests/testdata/extension/helper/FlowRule.json
Labels: area/flow-control, kind/enhancement

#231 Refine API and exported structure naming in core pkg
  api/slot_chain.go
  core/flow/slot.go
  core/log/slot.go
  core/stat/resource_node.go
  core/stat/resource_node_test.go
  core/stat/stat_prepare_slot.go
  core/stat/stat_slot.go
  core/system/slot.go
  core/system/slot_test.go
Labels: area/document, kind/enhancement

#235 API/flow/Circuit breaker doc.go
  api/api.go
  api/doc.go
  core/circuitbreaker/doc.go
  core/flow/doc.go
Labels: area/document

#170 enhance #169: integrate linters into CI
  .github/workflows/go.yml
  adapter/grpc/server_test.go
  core/hotspot/rule_manager_test.go
  core/hotspot/traffic_shaping.go
  core/stat/base/leap_array.go
  core/stat/base/leap_array_test.go
  core/stat/base/metric_bucket_test.go
  ext/datasource/consul/consul_test.go
  ext/datasource/helper_test.go
  logging/logging_test.go
  tests/core/circuitbreaker/circuitbreaker_slot_integration_test.go
Labels: kind/enhancement, to-review

#241 CI: Enhancement GithubActions.
  .github/workflows/go.yml
Labels: area/ci, kind/enhancement

#239 Refine GetResRule API and GetRules API in flow/circuitbreaker/hotspot/system module
  core/circuitbreaker/rule_manager.go
  core/circuitbreaker/slot.go
  core/circuitbreaker/stat_slot.go
  core/flow/rule_manager.go
  core/hotspot/rule_manager.go
  core/system/rule_manager.go
  core/system/rule_manager_test.go
  core/system/slot.go
  ext/datasource/helper_test.go
Labels: kind/enhancement, to-review

#238 Improve Config API
  api/init.go
  core/config/config.go
  core/config/entity.go
  core/log/metric/writer.go
  logging/logging.go
Labels: area/configuration, to-review

#243 Unify the type of rule.id as string
  core/flow/rule.go
  core/flow/rule_manager_test.go
  core/system/rule.go
  ext/datasource/helper_test.go
Labels: kind/enhancement, to-review

#217 Structure logging to json
  api/tracer.go
  core/base/entry.go
  core/base/slot_chain.go
  core/circuitbreaker/circuit_breaker.go
  core/circuitbreaker/rule_manager.go
  core/config/config.go
  core/flow/rule_manager.go
  core/flow/slot.go
  core/flow/tc_warm_up.go
  core/hotspot/cache/lru.go
  core/hotspot/concurrency_stat_slot.go
  core/hotspot/rule.go
  core/hotspot/rule_manager.go
  core/hotspot/slot.go
  core/hotspot/traffic_shaping.go
  core/log/metric/aggregator.go
  core/log/metric/reader.go
  core/log/metric/searcher.go
  core/log/metric/writer.go
  core/stat/base/bucket_leap_array.go
  core/stat/base/sliding_window_metric.go
  core/stat/node_storage.go
  core/system/rule_manager.go
  core/system/sys_stat.go
  example/datasource/nacos/nacos_example.go
  example/warm_up/qps_warm_up_example.go
  ext/datasource/consul/consul.go
  ext/datasource/etcdv3/etcdv3.go
  ext/datasource/file/refreshable_file.go
  ext/datasource/nacos/nacos.go
  ext/datasource/property.go
  logging/logging.go
  logging/logging_test.go
  tests/core/circuitbreaker/circuitbreaker_slot_integration_test.go
  util/auto_recover.go
Labels: area/logging, kind/refactor, to-review

#247 split isolation pkg to implement concurrency traffic control
  api/slot_chain.go
  core/base/result.go
  core/isolation/doc.go
  core/isolation/rule.go
  core/isolation/rule_manager.go
  core/isolation/rule_manager_test.go
  core/isolation/slot.go
  example/isolation/concurrency_limitation_example.go
Labels: area/flow-control, kind/refactor, to-review

#200 Support arbitrary statistic interval for flow control && stat parameters configurable
  adapter/echo/middleware_test.go
  adapter/gin/middleware_test.go
  api/slot_chain.go
  core/base/stat.go
  core/base/stat_test.go
  core/config/config.go
  core/config/entity.go
  core/flow/rule.go
  core/flow/rule_manager.go
  core/flow/rule_manager_test.go
  core/flow/slot.go
  core/flow/slot_test.go
  core/flow/standalone_stat_slot.go
  core/flow/tc_default.go
  core/flow/tc_throttling.go
  core/flow/tc_throttling_test.go
  core/flow/tc_warm_up.go
  core/flow/traffic_shaping.go
  core/stat/base/sliding_window_metric.go
  core/stat/base/sliding_window_metric_test.go
  core/stat/base_node.go
  core/stat/resource_node.go
  core/stat/stat_slot.go
  tests/testdata/extension/helper/FlowRule.json
Labels: area/flow-control, kind/feature, size/XXL, to-review

#256 enhance refreshable_file: watch source file event after remove/rename
  ext/datasource/consul/consul_test.go
  ext/datasource/file/refreshable_file.go
  ext/datasource/file/refreshable_file_test.go
  ext/datasource/nacos/nacos_test.go
  tests/testdata/extension/SystemRule.json
  tests/testdata/extension/SystemRule2.json
  tests/testdata/extension/SystemRule3.json
Labels: area/data-source, kind/enhancement, to-review
