Repository alibaba/sentinel-golang, pull requests merged in 2021-02, with the labels that each got.

#384 Embeded independent module in repo for datasource
  .github/workflows/go.yml
  pkg/datasource/consul/consul.go
  pkg/datasource/consul/consul_example_test.go
  pkg/datasource/consul/consul_test.go
  pkg/datasource/consul/demo/datasource_consul_example.go
  pkg/datasource/consul/doc.go
  pkg/datasource/consul/go.mod
  pkg/datasource/consul/go.sum
  pkg/datasource/consul/option.go
  pkg/datasource/etcdv3/demo/datasource_etcdv3_example.go
  pkg/datasource/etcdv3/doc.go
  pkg/datasource/etcdv3/etcdv3.go
  pkg/datasource/etcdv3/etcdv3_example.go
  pkg/datasource/etcdv3/etcdv3_test.go
  pkg/datasource/etcdv3/go.mod
  pkg/datasource/etcdv3/go.sum
  pkg/datasource/k8s/.gitignore
  pkg/datasource/k8s/Makefile
  pkg/datasource/k8s/PROJECT
  pkg/datasource/k8s/README.md
  pkg/datasource/k8s/api/v1alpha1/circuitbreakerrules_types.go
  pkg/datasource/k8s/api/v1alpha1/flowrules_types.go
  pkg/datasource/k8s/api/v1alpha1/groupversion_info.go
  pkg/datasource/k8s/api/v1alpha1/hotspotrules_types.go
  pkg/datasource/k8s/api/v1alpha1/isolationrules_types.go
  pkg/datasource/k8s/api/v1alpha1/systemrules_types.go
  pkg/datasource/k8s/api/v1alpha1/zz_generated.deepcopy.go
  pkg/datasource/k8s/config/crd/bases/datasource.sentinel.io_circuitbreakerrules.yaml
  pkg/datasource/k8s/config/crd/bases/datasource.sentinel.io_flowrules.yaml
  pkg/datasource/k8s/config/crd/bases/datasource.sentinel.io_hotspotrules.yaml
  pkg/datasource/k8s/config/crd/bases/datasource.sentinel.io_isolationrules.yaml
  pkg/datasource/k8s/config/crd/bases/datasource.sentinel.io_systemrules.yaml
  pkg/datasource/k8s/config/samples/datasource_v1alpha1_circuitbreakerrules.yaml
  pkg/datasource/k8s/config/samples/datasource_v1alpha1_flowrules.yaml
  pkg/datasource/k8s/config/samples/datasource_v1alpha1_hotspotrules.yaml
  pkg/datasource/k8s/config/samples/datasource_v1alpha1_isolationrules.yaml
  pkg/datasource/k8s/config/samples/datasource_v1alpha1_systemrules.yaml
  pkg/datasource/k8s/controllers/circuitbreakerrules_controller.go
  pkg/datasource/k8s/controllers/flowrules_controller.go
  pkg/datasource/k8s/controllers/hotspotrules_controller.go
  pkg/datasource/k8s/controllers/isolationrules_controller.go
  pkg/datasource/k8s/controllers/systemrules_controller.go
  pkg/datasource/k8s/go.mod
  pkg/datasource/k8s/go.sum
  pkg/datasource/k8s/k8s.go
  pkg/datasource/k8s/log_adapter.go
  pkg/datasource/k8s/log_adapter_test.go
  pkg/datasource/nacos/demo/datasource_nacos_example.go
  pkg/datasource/nacos/doc.go
  pkg/datasource/nacos/go.mod
  pkg/datasource/nacos/go.sum
  pkg/datasource/nacos/nacos.go
  pkg/datasource/nacos/nacos_test.go
Labels: area/data-source

#391 Embeded independent module in repo for adapters
  .github/workflows/go.yml
  go.sum
  pkg/adapters/echo/doc.go
  pkg/adapters/echo/go.mod
  pkg/adapters/echo/go.sum
  pkg/adapters/echo/middleware.go
  pkg/adapters/echo/middleware_example_test.go
  pkg/adapters/echo/middleware_test.go
  pkg/adapters/echo/option.go
  pkg/adapters/gear/doc.go
  pkg/adapters/gear/go.mod
  pkg/adapters/gear/go.sum
  pkg/adapters/gear/middleware.go
  pkg/adapters/gear/middleware_example.go
  pkg/adapters/gear/middleware_test.go
  pkg/adapters/gear/option.go
  pkg/adapters/gin/doc.go
  pkg/adapters/gin/go.mod
  pkg/adapters/gin/go.sum
  pkg/adapters/gin/middleware.go
  pkg/adapters/gin/middleware_example_test.go
  pkg/adapters/gin/middleware_test.go
  pkg/adapters/gin/option.go
  pkg/adapters/grpc/client.go
  pkg/adapters/grpc/client_test.go
  pkg/adapters/grpc/doc.go
  pkg/adapters/grpc/go.mod
  pkg/adapters/grpc/go.sum
  pkg/adapters/grpc/options.go
  pkg/adapters/grpc/server.go
  pkg/adapters/grpc/server_test.go
  pkg/adapters/micro/client.go
  pkg/adapters/micro/client_test.go
  pkg/adapters/micro/doc.go
  pkg/adapters/micro/go.mod
  pkg/adapters/micro/go.sum
  pkg/adapters/micro/options.go
  pkg/adapters/micro/server.go
  pkg/adapters/micro/server_test.go
  pkg/adapters/micro/test/test.pb.go
  pkg/adapters/micro/test/test.pb.micro.go
  pkg/adapters/micro/test/test.proto
Labels: area/integrations

#386 feat:block_err add opts func ,add RegistryBlockType func;
  core/base/block_error.go
  core/base/block_error_test.go
  core/base/result.go
  core/base/result_test.go
Labels: kind/enhancement
